export default {
  "0e384e19": [() => import(/* webpackChunkName: "0e384e19" */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  "17896441": [() => import(/* webpackChunkName: "17896441" */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  "1f391b9e": [() => import(/* webpackChunkName: "1f391b9e" */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  "393be207": [() => import(/* webpackChunkName: "393be207" */ "@site/src/pages/markdown-page.md"), "@site/src/pages/markdown-page.md", require.resolveWeak("@site/src/pages/markdown-page.md")],
  "4a1aad58": [() => import(/* webpackChunkName: "4a1aad58" */ "@site/docs/risk-assessment-tutorial.md"), "@site/docs/risk-assessment-tutorial.md", require.resolveWeak("@site/docs/risk-assessment-tutorial.md")],
  "4fb670b5": [() => import(/* webpackChunkName: "4fb670b5" */ "@generated/docusaurus-plugin-content-docs/default/p/open-atlas-docs-docs-c82.json"), "@generated/docusaurus-plugin-content-docs/default/p/open-atlas-docs-docs-c82.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/p/open-atlas-docs-docs-c82.json")],
  "5e95c892": [() => import(/* webpackChunkName: "5e95c892" */ "@theme/DocsRoot"), "@theme/DocsRoot", require.resolveWeak("@theme/DocsRoot")],
  "5e9f5e1a": [() => import(/* webpackChunkName: "5e9f5e1a" */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  "905e3b90": [() => import(/* webpackChunkName: "905e3b90" */ "@site/docs/plot-of-land.md"), "@site/docs/plot-of-land.md", require.resolveWeak("@site/docs/plot-of-land.md")],
  "a7456010": [() => import(/* webpackChunkName: "a7456010" */ "@generated/docusaurus-plugin-content-pages/default/__plugin.json"), "@generated/docusaurus-plugin-content-pages/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-pages/default/__plugin.json")],
  "a7bd4aaa": [() => import(/* webpackChunkName: "a7bd4aaa" */ "@theme/DocVersionRoot"), "@theme/DocVersionRoot", require.resolveWeak("@theme/DocVersionRoot")],
  "a94703ab": [() => import(/* webpackChunkName: "a94703ab" */ "@theme/DocRoot"), "@theme/DocRoot", require.resolveWeak("@theme/DocRoot")],
  "aba21aa0": [() => import(/* webpackChunkName: "aba21aa0" */ "@generated/docusaurus-plugin-content-docs/default/__plugin.json"), "@generated/docusaurus-plugin-content-docs/default/__plugin.json", require.resolveWeak("@generated/docusaurus-plugin-content-docs/default/__plugin.json")],
  "c4f5d8e4": [() => import(/* webpackChunkName: "c4f5d8e4" */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  "e718a1ec": [() => import(/* webpackChunkName: "e718a1ec" */ "@site/docs/risk-assessment.md"), "@site/docs/risk-assessment.md", require.resolveWeak("@site/docs/risk-assessment.md")],};
